# Generated by Django 3.1 on 2021-03-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210225_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='name',
        ),
        migrations.AddField(
            model_name='ability',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
