# Generated by Django 3.1 on 2021-03-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210306_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='last_access',
        ),
    ]
