# Generated by Django 3.1 on 2021-03-07 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_last_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_access',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 3, 7, 10, 53, 1, 269984, tzinfo=utc), default=datetime.datetime(2021, 3, 7, 10, 53, 26, 695632, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 3, 7, 10, 53, 1, 269954, tzinfo=utc)),
        ),
    ]
