# Generated by Django 3.1 on 2021-03-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210307_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_access',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
