# Generated by Django 3.1 on 2021-03-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210307_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('blog', 'code')},
        ),
    ]
