# Generated by Django 3.1 on 2021-03-08 11:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210307_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='filereference',
            name='storage_file',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/usr/src/api/media'), upload_to=''),
            preserve_default=False,
        ),
    ]
