# Generated by Django 3.1 on 2021-03-08 12:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_filereference_storage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereference',
            name='storage_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/usr/src/api/media/public'), upload_to=''),
        ),
    ]
