# Generated by Django 3.1 on 2021-03-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210308_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filereference',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='filereference',
            name='path',
        ),
        migrations.RemoveField(
            model_name='filereference',
            name='size',
        ),
        migrations.AlterField(
            model_name='filereference',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
