# Generated by Django 3.1 on 2021-03-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210308_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.postcontent'),
        ),
    ]
