# Generated by Django 3.1 on 2021-03-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210309_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DELETED', 'DELETED'), ('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('ARCHIVED', 'Archived'), ('NEW', 'New')], default='NEW', max_length=255),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='type',
            field=models.CharField(choices=[('LIST', 'List'), ('REVIEW', 'Review'), ('GALLERY', 'Gallery'), ('SHORT_POST', 'Short_Post'), ('NEWS', 'News'), ('EXTERNAL_RESOURCE', 'External_Resource'), ('LONG_READ', 'Long_Read')], default='SHORT_POST', max_length=255),
        ),
    ]
