fixtures:
  base_dir: blog.fixtures
  load:
    Role:
      module: load_1_ability
      class: LoadAbility
      attributes:
        quantity: 100
    Tag:
      module: load_2_tag
      class: LoadTag
      attributes:
        quantity: 20
